# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-6f2453c5-3a0c-4f0d-b71b-903cd25877c4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-6f2453c5-3a0c-4f0d-b71b-903cd25877c4".device = "/dev/disk/by-uuid/6f2453c5-3a0c-4f0d-b71b-903cd25877c4";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0014-32F6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-028a400a-4c66-41a9-b817-e219e24e0ce3"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
